
services:
  nginx:
    image: nginx:inception
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - /home/mel-akar/data/wordpress:/var/www/wordpress
    restart: always
    networks:
      - inception
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    restart: always
    volumes:
      - /home/mel-akar/data/mariadb:/var/lib/mysql 
    networks:
      - inception
    healthcheck:
        test: ["CMD", "mariadb-admin", "ping"]
        # interval: 30s by default is 30
        timeout: 10s
        retries: 5
  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
    env_file :
      - .env
    volumes:
      - /home/mel-akar/data/wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
  redis:
    image: redis:inception
    container_name: redis
    build: ./requirements/bonus/redis/
    env_file :
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
        test: ["CMD", "redis-cli", "-h", "localhost", "-p", "1234", "ping"]
        timeout: 10s
        retries: 5
  static_webp:
    image: webp:inception
    container_name: webp
    build: ./requirements/bonus/static_wpage/
    env_file :
      - .env
    ports:
      - "8080:8080"
    restart: always
  ftp_server:
    image: ftp_server:inception
    container_name: ftp_server
    build: ./requirements/bonus/ftp_server/
    env_file:
      - .env
    volumes:
      - /home/mel-akar/data/wordpress:/var/www/wordpress
    ports:
      - "20:20"
      - "21:21"
      - "50000-50120:50000-50120"
    restart: always
  irc_server:
    image: irc_server:inception
    container_name: irc_server
    build: ./requirements/bonus/extra_service/
    ports:
      - "1337:1337"
    env_file:
      - .env
    restart: always

networks:
  inception:
    driver: bridge
    name: inception

# should add health check for wp to check if mariadb is ready & redis