# volumes:
#   mariadb:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: /home/mel-akar/data/mariadb
#       o: bind
#       type: none
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       device: /home/mel-akar/data/wordpress
#       o: bind
#       type: none



services:
  nginx:
    image: nginx:inception
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - /home/mel-akar/data/wordpress:/var/www/wordpress
    restart: always
    networks:
      - inception
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    # ports:
    #   - "3306:3306"
    restart: always
    volumes:
      - /home/mel-akar/data/mariadb:/var/lib/mysql 
    networks:
      - inception
  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
      - redis
    env_file :
      - .env
    volumes:
      - /home/mel-akar/data/wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
  redis:
    image: redis:inception
    container_name: redis
    build: ./requirements/bonus/redis/
    env_file :
      - .env
    networks:
      - inception
    restart: always
  static_webp:
    image: webp:inception
    container_name: webp
    build: ./requirements/bonus/static_wpage/
    env_file :
      - .env
    ports:
      - "8080:8080"
    restart: always

networks:
  inception:
    driver: bridge
    name: inception

# should add health check for wp to check if mariadb is ready & redis